name: sprut
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+1007

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  location: ^4.3.0
  flutter_bloc: ^7.0.0
  provider: ^6.0.2
  get_it: ^7.2.0
  dio: ^4.0.6
  custom_info_window: ^1.0.1
  flutter_keyboard_visibility: ^5.2.0
  shared_preferences: ^2.0.13
  connectivity_plus: ^2.3.0
  fl_location: ^1.2.1
  snapping_sheet: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  get: ^4.6.1
  flutter_polyline_points: ^1.0.0
  equatable: ^2.0.3
  flutter_overlay_loader: ^1.0.3
  modal_bottom_sheet: ^2.0.1
  google_maps_flutter: ^2.2.1
  flutter_otp_text_field: ^1.0.1
  lottie: ^1.3.0
  pin_code_fields: ^7.4.0
  geocoding: ^2.0.4
  sizer: ^2.0.15
  flutter_svg: ^1.0.3
  flutter_native_splash: ^2.1.6
  logger: ^1.1.0
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.7
  share_plus: ^2.0.0
  firebase_messaging: 13.0.3
  firebase_core: ^1.22.0
  flutter_local_notifications: ^12.0.4
  firebase_crashlytics: ^2.9.0
  collection: ^1.15.0
  grouped_list: ^5.1.2
  jiffy: ^5.0.0
  timezone: ^0.9.0
  geolocator: ^9.0.2
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter_native_splash:
   image: "assets/images/logo_withName.png"
   color:  "#ffffff"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/tariffs/
    - assets/payments/
    - assets/services/
    - assets/about/
    - assets/settings/
    - assets/fooddelivery/
  
  fonts:
    - family: SF-Pro Display
      fonts:
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYMEDIUM.OTF
          weight: 300
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 600
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYBOLD.OTF
          weight: 900

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
